### PR TITLE
Wellness UI tweaks

### PR DESCRIPTION
**Pull request by wal**
Hi Tyler, 

Am working my way through the code nice and slowly to understand it all and learn from it ... and making a few little tweaks as I go .. hope thats ok, if you dont like these changes its obviously no problem not merging them in .. 

1. I added a "compliance" guage. How many of the squad have wellness screened today
2. I changed up the format of the who didnt screen and alerts lists, I wasnt so happy with how they looked after my attempt yesterday
3. I tweaked the daily and weekly wellness plots.
4. cleaned up some code along the way

What do you think   ?

Before .. 
screen shot 2018-05-11 at 15 29 49

After ...

screen shot 2018-05-11 at 15 29 32

### CODE REVIEW

**Comment by tabosch** [comment]
Wal, really like the changes, I had mad a few tweaks to your lists last night to add some scrolling so you could read all the names, but I like this new format. I also really like the color scheme in the daily plot, I will probably add back in the red line for the week wellness as a reference though.

**Comment by wal** [comment]
ok cool, yeah I wasn't sure if the 'redness' of the point/line was enough to be able to figure out that it was extreme (<2.5) .. but you are right it should be explicit with its own  line 👍

**Comment by tabosch** [comment]
I am already learning some new tricks from your code additions so that is awesome!!! Plus it helps having someone go through my code that I hacked together from several projects to catch redundancies is a huge help. I may send over a drill calculator that I built awhile back and see if you can find some better ways to do it as its a bit slow and cumbersome.

**Comment by wal** [comment]
I totally understand things being put together with bits of other stuff, I have a whole github profile full of projects like that :)

yeah I love going through and refactoring code like its a great way to figure out how something works and figure out new ways to do stuff along the way.

sure send it on, happy to help if I can.

**Pull request merged**
